spring:
  cloud:
    config:
      import: "configserver:http://localhost:8888" 
    discovery:
      enabled: true 

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
    registerWithEureka: true
    fetchRegistry: true
