spring:
  application:
    name: gatewayserver
  cloud:
    config:
      profile: local
  config:
    import: "configserver:${configUrl}"


configUrl: http://localhost:8888

server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
    registerWithEureka: true
    fetchRegistry: true
