spring:
  cloud:
    config:
      import: "configserver:http://localhost:8888" # Point to your Config Server URL
    discovery:
      enabled: true # Enable service discovery

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
    registerWithEureka: true
    fetchRegistry: true
