server:
  port: 8888 

spring:
  application:
    name: orderservice

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
    registerWithEureka: true
    fetchRegistry: true

